# This is a basic workflow to help you get started with Actions

name: test2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: ls
        run: ls -al

      # Runs a set of commands using the runners shell
      - name: echo
        run: echo "this is checkout"

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
       
      - name: chmod gradle
        run: chmod -X ./gradlew
        
      - name: build
        run: gradle build
        
      - name: build check
        run: ls ./build/libs
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: copy war
        run: cp ./build/libs/my-spring-board-0.0.1-SNAPSHOT.war ./Dockerfile/my-spring-board-0.0.1-SNAPSHOT.war
                
      - name: docker build
        run: |
         docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_github_ver${{ GITHUB_RUN_NUMBER }} ./Dockerfile
         docker images
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_github_ver${{ GITHUB_RUN_NUMBER }}
         
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: cluster-1
          location: us-central1-c
          project_id: teak-runner-343008
          credentials: ${{ secrets.GCP_SA_KEY }}
          
      - name: was-deploy-restart
        run: kubectl rollout restart deployment/tomcat-was
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        
      - name: change file name
        run: |
          DATE=$(date +%y-%m-%d-%H:%M)
          mv ./build/libs/*.war ./build/libs/$DATE.war
        
      - name: Cloud Storage upload
        run: gsutil cp ./build/libs/*.war gs://storagepsc
